name: Swift Debug CV

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  exec-cv-debug:
    runs-on: aeroconf 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Clear cache
        run: |
          swift package purge-cache || true
          swift package reset
          swift package clean

      - name: Build Tests (Linux host)
        if: ${{ runner.os == 'Linux' }}
        run: |
          PKG_CONFIG_PATH="/usr/local/armv7-unknown-linux-gnueabihf/staging/lib/pkgconfig:${PKG_CONFIG_PATH}" swift build --build-tests --destination /usr/local/armv7-unknown-linux-gnueabihf/destination.json

      - name: Run Tests
        run: |
          scp .build/armv7-unknown-linux-gnueabihf/debug/${{ github.event.repository.name }}PackageTests.xctest root@zybo.local:~
          ssh root@zybo.local bash -ic /home/root/${{ github.event.repository.name}}PackageTests.xctest 
          ssh root@zybo.local rm ${{ github.event.repository.name }}PackageTests.xctest      

      - name: Get Kripke Structure
        run: scp root@zybo.local:~/0.xml .

      - name: Perform Verification
        run: |
          echo "OUTPUT=`verifyta 0.xml 0.xml.q --summary`" >> "$GITHUB_ENV"
          echo "RESULT=`echo $OUTPUT | grep NOT`" > "$GITHUB_ENV"
          # if [ -n $RESULT ]; then exit 1; fi

      - name: Output Error
        if: ${{ env.RESULT != '' }}
        run: exit 1

